FROM ghcr.io/rhadp/builder:latest

USER root

# install jumpstarter and other python dependencies
ENV JUMPSTARTER_VERSION=main \
    JUMPSTARTER_REPO=https://github.com/rhadp/jumpstarter
COPY requirements.txt /tmp/requirements.txt
RUN uv venv /venv && \
    uv pip install "git+${JUMPSTARTER_REPO}@${JUMPSTARTER_VERSION}#subdirectory=packages/jumpstarter-all" && \
    uv pip install -r /tmp/requirements.txt

# init scripts, create directories, and set permissions in a single layer
#COPY init-git ${INIT_SCRIPTS_DIR}/init-git

# A last pass to make sure that an arbitrary user can write in $HOME
RUN chgrp -R 0 /home && chmod -R g=u /home

# back to the user
USER 10001