FROM ghcr.io/rhadp/builder:latest

USER root

# install jumpstarter and other python dependencies
COPY requirements.txt /tmp/requirements.txt
RUN uv pip install "git+https://github.com/rhadp/jumpstarter@develop#subdirectory=packages/jumpstarter-all" && \
    uv pip install -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt

# init scripts, create directories, and set permissions in a single layer
COPY init-git ${INIT_SCRIPTS_DIR}/init-git

RUN mkdir -p /home/user/.config/jumpstarter/clients/ && \
    chmod +x ${INIT_SCRIPTS_DIR}/* 

USER user