FROM ghcr.io/rhadp/runtime:latest

ARG TARGETARCH
USER root

# add additional scripts
COPY s3-upload.py /home/user/s3-upload.py

# install additional python dependencies and set permissions in a single layer
COPY requirements.txt /tmp/requirements.txt
RUN uv pip install -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt

# A last pass to make sure that an arbitrary user can write in $HOME
RUN chgrp -R 0 /home && chmod -R g=u /home

USER 10001
