FROM ghcr.io/rhadp/runtime:latest

USER root

ARG TARGETARCH

ENV ARCH=${TARGETARCH:-arm64} \
    HOME=/opt/app-root/src \
    APP_ROOT=/opt/app-root \
    XDG_CONFIG_HOME=/opt/app-root/.config \
    PATH=/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# add additional scripts
#COPY s3-upload.py /home/user/s3-upload.py

# install additional python dependencies and set permissions in a single layer
COPY requirements.txt /tmp/requirements.txt
RUN uv pip install -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt

# A last pass to make sure that an arbitrary user can write in $HOME
RUN chgrp -R 0 ${APP_ROOT} && chmod -R g=u ${APP_ROOT}

USER 1001
