#!/usr/bin/env bash
#set -euo pipefail
set -x

GIT_PAT_NAME="${GIT_PAT_NAME:-personal-access-token-git-pac}"
NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)

CONSOLE_URL=$(oc whoami --show-console)
BASE_URL=${CONSOLE_URL#https://console-openshift-console.}

# PAC endpoint setup
PAC_ENDPOINT="https://pipelines-as-code-controller-openshift-pipelines.$BASE_URL"

# Create the webhook secret and retrieve the git PAT
WEBHOOK_SECRET=$(openssl rand -hex 20)
GIT_PAT=$(oc -n $NAMESPACE get secret $GIT_PAT_NAME -o jsonpath='{.data.token}' | base64 -d)

# Create the webhook config secret
if oc get secret github-webhook-config -n "$NAMESPACE" &>/dev/null; then
  oc delete secret github-webhook-config -n "$NAMESPACE"
fi

oc -n $NAMESPACE create secret generic github-webhook-config \
  --from-literal provider.token="$GIT_PAT" \
  --from-literal webhook.secret="$WEBHOOK_SECRET"

# Create the webhook on the upstream GitHub repository
GIT_REMOTE_URL=$(git remote get-url origin)
GIT_REPO=${GIT_REMOTE_URL#*github.com[:/]}
GIT_REPO=${GIT_REPO%.git}

HOOK_EXISTS=$(curl -sS \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${GIT_PAT}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "https://api.github.com/repos/${GIT_REPO}/hooks" \
  | jq -e --arg url "$PAC_ENDPOINT" '.[] | select(.config.url == $url)')

if [[ -n "$HOOK_EXISTS" ]]; then
  echo "Webhook already exists, deleting it"
  HOOK_ID=$(echo "$HOOK_EXISTS" | jq -r '.id')
  curl -sS -X DELETE \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer ${GIT_PAT}" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "https://api.github.com/repos/${GIT_REPO}/hooks/${HOOK_ID}"
fi

curl -sS -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${GIT_PAT}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  "https://api.github.com/repos/${GIT_REPO}/hooks" \
  -d @- <<EOF
{
  "name": "web",
  "active": true,
  "events": ["push", "pull_request", "issue_comment", "commit_comment"],
  "config": {
    "url": "${PAC_ENDPOINT}",
    "content_type": "json",
    "insecure_ssl": "0",
    "secret": "${WEBHOOK_SECRET}"
  }
}
EOF

# create the Repository CR
cat > /tmp/cr.yaml <<EOF
apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ${GIT_REPO##*/}
  namespace: ${NAMESPACE}
spec:
  url: "https://github.com/${GIT_REPO}"
  git_provider:
    secret:
      name: "github-webhook-config"
      key: "provider.token" # Set this if you have a different key in your secret
    webhook_secret:
      name: "github-webhook-config"
      key: "webhook.secret" # Set this if you have a different key for your secret
EOF
oc apply -f /tmp/cr.yaml && rm -f /tmp/cr.yaml