# caib builder container
FROM registry.redhat.io/ubi10/go-toolset:latest as builder

ARG TARGETARCH
ENV CGO_ENABLED=0 GOARCH=${TARGETARCH}

ENV BUILDER_REPO=https://github.com/mickume/automotive-dev-operator \
    BUILDER_VERSION=develop

# build the caib tool
RUN git clone -b ${BUILDER_VERSION} ${BUILDER_REPO} && \
    cd automotive-dev-operator && \
    VERSION="$(git rev-parse --short HEAD)-develop" make build-caib && \
    chmod +x bin/caib && \
    cp bin/caib /opt/app-root/src/caib && \
    /opt/app-root/src/caib --version