FROM ghcr.io/rhadp/base:latest

USER root

# $PROFILE_EXT contains all additions made to the bash environment
ENV PROFILE_EXT=/etc/profile.d/udi_environment.sh
RUN touch ${PROFILE_EXT} && chown user ${PROFILE_EXT}

# install common development packages
RUN dnf install -y --setopt=tsflags=nodocs \
    autoconf patch lsof redhat-rpm-config \
    openssl-devel libcurl-devel libxml2-devel libxslt-devel zlib-devel \
    unzip wget bzip2 zip \
    llvm-toolset \
    gdb cmake automake autoconf make && \
    dnf -y clean all --enablerepo='*' && \
    rm -rf /var/cache/dnf

# install c/c++ development packages
RUN dnf install -y --setopt=tsflags=nodocs \
    gcc gcc-c++ clang clang-libs clang-tools-extra && \
    dnf -y clean all --enablerepo='*' && \
    rm -rf /var/cache/dnf

# already installed: go, python, java, node

# install rust
ENV CARGO_HOME=/home/tooling/.cargo \
    RUSTUP_HOME=/home/tooling/.rustup \
    PATH=/home/tooling/.cargo/bin:${PATH}

RUN mkdir -p /home/tooling/.cargo && \
    mkdir -p /home/tooling/.rustup && \
    curl --proto '=https' --tlsv1.2 -sSfo rustup https://sh.rustup.rs && \
    chmod +x rustup && \
    mv rustup /usr/bin/ && \
    rustup -y --no-modify-path --profile minimal -c rust-src -c rust-analysis -c rls

RUN chgrp -R 0 /home/user /home/tooling && chmod -R g=u /home/user /home/tooling

USER 10001
