FROM registry.access.redhat.com/ubi9/s2i-core:9.7
# https://catalog.redhat.com/en/software/containers/ubi9/s2i-core/61fb9fa7891fad8774b86e06?architecture=arm64&image=#containerfile

USER root

# install centos stream & fedora repos, other vars
ENV CENTOS_RELEASE=9.0-36 \
    APP_ROOT=/home/tooling \
    ARCH=${TARGETARCH:-arm64}

# protobuf compiler path
ENV PATH="/home/tooling/protobuf/bin:$PATH" \
    PROTOBUF_HOME="/home/tooling/protobuf"

# install rust
ENV CARGO_HOME=${APP_ROOT}/.cargo \
    RUSTUP_HOME=${APP_ROOT}/.rustup \
    PATH=${APP_ROOT}/.cargo/bin:${PATH}

    # set the virtual environment for jumpstarter etc
ENV UV_PYTHON=python3.12 VIRTUAL_ENV=/venv

# install centos stream & fedora repos
RUN if [ "$ARCH" = "arm64" ]; then \
        dnf install -y --setopt=tsflags=nodocs \
        https://mirror.stream.centos.org/9-stream/BaseOS/aarch64/os/Packages/centos-stream-repos-${CENTOS_RELEASE}.el9.noarch.rpm \
        https://mirror.stream.centos.org/9-stream/BaseOS/aarch64/os/Packages/centos-gpg-keys-${CENTOS_RELEASE}.el9.noarch.rpm; \
    else \
        dnf install -y --setopt=tsflags=nodocs \
        https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/centos-stream-repos-${CENTOS_RELEASE}.el9.noarch.rpm \
        https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/centos-gpg-keys-${CENTOS_RELEASE}.el9.noarch.rpm; \
    fi && \
    dnf install -y --setopt=tsflags=nodocs \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm

# install basic packages and common development dependencies
RUN dnf install -y --setopt=tsflags=nodocs \
    python3.12 python3.12-devel python3-pip \
    git jq yq \
    nss_wrapper kmod openssh-clients nc stow \
    fuse-overlayfs slirp4netns shadow-utils \
    patch lsof redhat-rpm-config procps-ng \
    unzip wget bzip2 zip which

# install development dependencies
RUN dnf install -y epel-release && \
    dnf install -y --setopt=tsflags=nodocs \
        gdb gd-devel cmake automake autoconf make \
        gcc gcc-c++ \
        glibc-devel \
        openssl-devel \
        sqlite-devel \
        zlib-devel libcurl-devel libpq-devel \
        libxml2-devel libxslt-devel 

# install node
RUN dnf install -y epel-release && \
    dnf install -y --setopt=tsflags=nodocs \
        npm 
    
RUN mkdir -p $RUSTUP_HOME $CARGO_HOME && \
    curl --proto '=https' --tlsv1.2 -sSfo rustup https://sh.rustup.rs && \
    chmod +x rustup && mv rustup /usr/bin/ && \
    rustup -y --no-modify-path --profile minimal -c rust-src -c rust-analysis -c rls

# install protobuf compiler
RUN mkdir -p /home/tooling/protobuf && \
    if [ "$ARCH" = "arm64" ]; then \
        URL=$(curl -s https://api.github.com/repos/protocolbuffers/protobuf/releases/latest \
        | jq -r '.assets[] | select(.name | endswith("linux-aarch_64.zip")) | .browser_download_url') && \
        curl -LO "$URL"; \
    else \
        URL=$(curl -s https://api.github.com/repos/protocolbuffers/protobuf/releases/latest \
        | jq -r '.assets[] | select(.name | endswith("linux-x86_64.zip")) | .browser_download_url') && \
        curl -LO "$URL"; \
    fi && \
    unzip "$(basename "$URL")" -d "/home/tooling/protobuf"

# install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv  /bin/uv
COPY --from=ghcr.io/astral-sh/uv:latest /uvx /bin/uvx

# clean up
RUN dnf -y clean all --enablerepo='*' && \
    rm -rf /var/cache/dnf

# Reset permissions of modified directories
RUN rpm-file-permissions && chown -R 1001:0 ${APP_ROOT}