FROM registry.access.redhat.com/ubi9/ubi:9.7 

ARG TARGETARCH
USER root

# install centos stream & fedora repos
ENV CENTOS_RELEASE=9.0-34
RUN if [ "$TARGETARCH" = "arm64" ]; then \
        dnf install -y --setopt=tsflags=nodocs \
        https://mirror.stream.centos.org/9-stream/BaseOS/aarch64/os/Packages/centos-stream-repos-${CENTOS_RELEASE}.el9.noarch.rpm \
        https://mirror.stream.centos.org/9-stream/BaseOS/aarch64/os/Packages/centos-gpg-keys-${CENTOS_RELEASE}.el9.noarch.rpm; \
    else \
        dnf install -y --setopt=tsflags=nodocs \
        https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/centos-stream-repos-${CENTOS_RELEASE}.el9.noarch.rpm \
        https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/centos-gpg-keys-${CENTOS_RELEASE}.el9.noarch.rpm; \
    fi && \
    dnf install -y --setopt=tsflags=nodocs \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm

# install basic packages & virtualization packages
RUN dnf install -y --setopt=tsflags=nodocs \
    python3.12 python3.12-devel python3-pip \
    git jq yq \
    nss_wrapper kmod openssh-clients nc stow \
    fuse-overlayfs slirp4netns shadow-utils \
    python3-libgpiod nss_wrapper \
    qemu-kvm qemu-img libvirt \
    "@virtualization-hypervisor" "@virtualization-client" "@virtualization-platform" "@virtualization-tools" \
    virt-install virt-viewer \
    genisoimage && \
    dnf -y clean all --enablerepo='*' && \
    rm -rf /var/cache/dnf

# install oc and kubectl
ENV OC_VERSION=4.20 \
    K8S_VERSION=1.33 KUBECONFIG=/home/user/.kube/config

# oc client
RUN if [ "$TARGETARCH" = "arm64" ]; then \
        curl -L https://mirror.openshift.com/pub/openshift-v4/arm64/clients/ocp/stable-${OC_VERSION}/openshift-client-linux.tar.gz; \
    else \
        curl -L https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable-${OC_VERSION}/openshift-client-linux.tar.gz; \
    fi | tar -C /usr/local/bin -xz --no-same-owner && \
    chmod +x /usr/local/bin/oc
  
## kubectl
RUN <<EOF
set -euf -o pipefail

cat <<EOF2 > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://pkgs.k8s.io/core:/stable:/v${K8S_VERSION}/rpm/
enabled=1
gpgcheck=1
gpgkey=https://pkgs.k8s.io/core:/stable:/v${K8S_VERSION}/rpm/repodata/repomd.xml.key
EOF2

dnf install --setopt=tsflags=nodocs -y kubectl
curl -sSL -o ~/.kubectl_aliases https://raw.githubusercontent.com/ahmetb/kubectl-alias/master/.kubectl_aliases
EOF

# python dependencies
COPY --from=ghcr.io/astral-sh/uv:latest /uv  /bin/uv
COPY --from=ghcr.io/astral-sh/uv:latest /uvx /bin/uvx

# set the virtual environment for jumpstarter etc
ENV UV_PYTHON=python3.12 VIRTUAL_ENV=/venv

# install python dependencies, jumpstarter, create directories, and set permissions in a single layer
ENV JUMPSTARTER_VERSION=main \
    JUMPSTARTER_REPO=https://github.com/rhadp/jumpstarter
COPY requirements.txt /tmp/requirements.txt
RUN uv venv /venv && \
    uv pip install "git+${JUMPSTARTER_REPO}@${JUMPSTARTER_VERSION}#subdirectory=packages/jumpstarter-all" && \
    uv pip install -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt && \
    mkdir -p /etc/jumpstarter/exporters && \
    mkdir -p /home/user/.config/jumpstarter/clients/ && \
    chgrp -R 0 /home/user && chmod -R g=u /home/user

USER 10001
