# https://catalog.redhat.com/en/software/containers/ubi10/66f2a8d39bdbdc1b74e81460#overview
FROM registry.redhat.io/ubi10:10.2

USER root

ARG TARGETARCH

ENV ARCH=${TARGETARCH:-arm64} \
    HOME=/opt/app-root/src \
    APP_ROOT=/opt/app-root \
    XDG_CONFIG_HOME=/opt/app-root/.config \
    PATH=/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# set the virtual environment
ENV UV_PYTHON=python3.14 VIRTUAL_ENV=/venv

# install this version of jumpstarter, tkn etc
ENV JUMPSTARTER_REPO=https://github.com/mickume/jumpstarter \
    JUMPSTARTER_VERSION=develop \
    TKN_VERSION=1.23.0 \
    OC_VERSION=4.21 \
    K8S_VERSION=1.34
    
# install epel releases
RUN dnf install -y --setopt=tsflags=nodocs https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm && \
    dnf install -y epel-release 

# install basic packages
RUN dnf install -y --setopt=tsflags=nodocs \
    nss_wrapper kmod openssh-clients nc \
    fuse-overlayfs passt shadow-utils \
    patch lsof redhat-rpm-config procps-ng \
    unzip wget bzip2 zip which rpm-build \
    openssl openssl-devel \
    python3.14 python3.14-devel python3-pip \
    git jq  yq

ENV KUBECONFIG=${APP_ROOT}/.kube/config

# oc client
RUN if [ "$ARCH" = "arm64" ]; then \
        curl -L https://mirror.openshift.com/pub/openshift-v4/arm64/clients/ocp/stable-${OC_VERSION}/openshift-client-linux.tar.gz; \
    else \
        curl -L https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable-${OC_VERSION}/openshift-client-linux.tar.gz; \
    fi | tar -C /usr/local/bin -xz --no-same-owner && \
    chmod +x /usr/local/bin/oc
  
## kubectl
RUN <<EOF
set -euf -o pipefail

cat <<EOF2 > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://pkgs.k8s.io/core:/stable:/v${K8S_VERSION}/rpm/
enabled=1
gpgcheck=1
gpgkey=https://pkgs.k8s.io/core:/stable:/v${K8S_VERSION}/rpm/repodata/repomd.xml.key
EOF2

dnf install --setopt=tsflags=nodocs -y kubectl
EOF

# Install the tkn CLI
RUN mkdir -p /home/tooling/bin && \
    if [ "${ARCH}" = "arm64" ]; then \
        curl -fsSL "https://mirror.openshift.com/pub/cgw/pipelines/${TKN_VERSION}/tkn-linux-arm64.tar.gz" | tar xz -C /usr/local/bin; \
    else \
        curl -fsSL "https://mirror.openshift.com/pub/cgw/pipelines/${TKN_VERSION}/tkn-linux-amd64.tar.gz" | tar xz -C /usr/local/bin; \
    fi && \
    chmod +x /usr/local/bin/tkn

# install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv  /bin/uv
COPY --from=ghcr.io/astral-sh/uv:latest /uvx /bin/uvx

# copy the caib tool
COPY --from=ghcr.io/rhadp/tools:latest /opt/app-root/src/caib /usr/local/bin/caib
RUN caib --version

# install jumpstarter & other python dependencies
COPY requirements.txt /tmp/requirements.txt

RUN uv venv --clear /venv && \
    uv pip install -r /tmp/requirements.txt && \
    uv pip install "git+${JUMPSTARTER_REPO}@${JUMPSTARTER_VERSION}#subdirectory=python/packages/jumpstarter-all" && \
    rm -rf /tmp/requirements.txt

# clean up
RUN dnf -y clean all --enablerepo='*' && \
    rm -rf /var/cache/dnf

# Directory with the sources is set as the working directory so all scripts
# can execute relative to this path.
WORKDIR ${HOME}

# Reset permissions of modified directories and add default user
RUN useradd -u 1001 -r -g 0 -d ${HOME} -c "Default Application User" default && \
    chown -R 1001:0 ${APP_ROOT}

USER 1001
